Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;

namespace AspNetCoreTodo.Models {
    public class NotApplicationUser : IdentityUser
    {
    }
}

Models/ErrorViewModel.cs
using System;

namespace AspNetCoreTodo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/RedirectsViewModel.cs
namespace AspNetCoreTodo.Models
{
    public class RedirectsViewModel
    {
        public URLRedirect[] 
        Redirects { get; set; }
    }
}

Models/URLRedirect.cs
using System;
using System.ComponentModel.DataAnnotations;
namespace AspNetCoreTodo.Models
{
    public class URLRedirect
    {
        [KeyAttribute]
        public string Id { get; set; }
        public string UserId { get; set; }
        [Required]
        public string DestinationUrl { get; set; }
        public long NumVisits { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AspNetCoreTodo.Models;

namespace AspNetCoreTodo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogDebug("Home index loaded");

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RedirectAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AspNetCoreTodo.Services;
using AspNetCoreTodo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace AspNetCoreTodo.Controllers
{
    [Authorize]
    public class RedirectAdminController : Controller
    {
        private readonly IRedirectService _redirectService;
        private readonly UserManager<IdentityUser> _userManager;
        public RedirectAdminController(IRedirectService redirectService, UserManager<IdentityUser> userManager)
        {
            _redirectService = redirectService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(){
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null) return Challenge();
            var redirects = await _redirectService.GetRedirectsForUserAsync(currentUser);
            var model = new RedirectsViewModel() {
                Redirects = redirects
            };
            return View(model);
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRedirect(URLRedirect newRedirect)
        {
            if (!ModelState.IsValid) {
                return RedirectToAction("Index");
            }
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null) return Challenge();
            newRedirect.UserId=currentUser.Id;
            var successful = await _redirectService.AddRedirectAsync(newRedirect);
            if (!successful) {
                return BadRequest("Could not add item.");
            }
            return RedirectToAction("Index");
        }


    }
}

Controllers/RedirectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AspNetCoreTodo.Services;
using AspNetCoreTodo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace AspNetCoreTodo.Controllers
{
    [Route("r")]
    public class RedirectController : Controller
    {
        private readonly IRedirectService _redirectService;
        public RedirectController(IRedirectService redirectService)
        {
            _redirectService = redirectService;
        }
        [HttpGet("{id}")]
        public async Task<IActionResult> DoRedirect(string id){
            var redirect = await _redirectService.VisitRedirectAsync(id);
            return new RedirectResult(redirect.DestinationUrl,false);
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is an example ASP.Net core application. It allows you to redirect a short name to a different URL, and provides an administrative interface to do so.</p>
</div>

Views/RedirectAdmin/AddRedirectPartial.cshtml
@model URLRedirect

<form asp-action="AddRedirect" method="POST">
    <label asp-for="Id">Id/Short string:</label>
    <input asp-for="Id">
    <label asp-for="DestinationUrl">Destination URL:</label>
    <input asp-for="DestinationUrl">
    <button type="submit">Add</button>
</form>

Views/RedirectAdmin/Index.cshtml
@model RedirectsViewModel

@{
    ViewData["Title"] = "Your Redirects";
}
<div class="panel panel-default todo-panel">
    <div class="panel-heading">@ViewData["Title"]</div>
    <table class="table table-hover">
    <thead>
    <tr>
        <td>Id</td>
        <td>Destination Url</td>
        <td>Visits</td>
    </tr>
    </thead>
    @foreach (URLRedirect redirect in Model.Redirects)
    {
        <tr>
            <td>@redirect.Id</td>
            <td>@redirect.DestinationUrl</td>
            <td>@redirect.NumVisits</td>
        </tr>
    }
    </table>
    <div class="panel-footer add-item-form">
        @await Html.PartialAsync("AddRedirectPartial", new URLRedirect())
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - URL Redirector</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Url Redirector</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RedirectAdmin" asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Url Redirector - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>